import './globals.css'
import { Roboto } from 'next/font/google'
import Nav from './nav'
import Footer from './footer'
import Providers from './provider'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['100', '400'],
  style: 'normal',
  display: 'swap',
  subsets: ['latin'] 
})



export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + 'api/v1/products', { next: { revalidate: 10 }})
  const data = await res.json();
  const productlist = data.products
  
  return (
    
    <html lang="en">
      <head />
      <Providers>
        <body className={roboto.className}>
          <Nav products={productlist}/>
              {children}
          <Footer />
        </body>
        </Providers>
    </html>
  )
}

