import './globals.css'
import { Roboto } from 'next/font/google'
import Nav from './nav'
import Footer from './footer'
import Providers from './provider'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['300'],
  style: 'normal',
  display: 'swap',
  subsets: ['latin'] 
})


export default function RootLayout({ children }) {
  
  return (
    
    <html lang="en">
      <head />
      <Providers>
        <body className={roboto.className}>
          <Nav />
              {children}
          <Footer />
        </body>
        </Providers>
    </html>
  )
}

