###
POST http://localhost:10000/api/v1/login
Content-Type: application/json

{
  "email": "21437262@student.uwl.ac.uk",
  "passwd": "1"
}

###
POST http://localhost:10000/api/v1/register
Content-Type: application/json

{
    "fullname": "Artem Radionov",
    "dob": "12-12-1996",
    "gender": "male",
    "mob_phone": "123456789",
    "email": "21437262@student.uwl.ac.uk",
    "passwd": "1"
}


### 
GET http://localhost:10000/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjIxNDM3MjYyQHN0dWRlbnQudXdsLmFjLnVrIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgwMzA1ODE0LCJleHAiOjE2ODAzMDY3MTR9.pKsayJ84NmCQKBT3jgt971EVGPyjOfQO-dxMuzjzVk0

###
GET http://localhost:10000/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjIxNDM3MjYyQHN0dWRlbnQudXdsLmFjLnVrIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgwMzA1ODE0LCJleHAiOjE2ODAzMDY3MTR9.pKsayJ84NmCQKBT3jgt971EVGPyjOfQO-dxMuzjzVk0

